[package]
name = "ex01-saying-hello"
version = "0.1.0"
authors = ["shaolang <shaolang@ymail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
